### ISSUE TITLE
Resident 클래스와 Neighborhood 클래스에서 figureNextState 메소드 분리

### ISSUE THREAD

**Issue by sikutisa** [cau-design-pattern-team-10/design-pattern-team-10#30]
- Resident 클래스와 Neighborhood 클래스에서 figureNextState 메소드를 분리하여 코드 가독성을 높입니다.
- 기존에 Resident 클래스를 개선하는 이슈와 Neighborhood를 개선하는 이슈가 별도로 존재하였습니다.
    - 하지만 작업이 진행됨에 따라 두 클래스에서 동일하게 figureNextState 메소드를 분리하는 작업을 진행하게 됐습니다.
    - 따라서, 이 이슈를 메소드 분리에 대한 이슈로 변경하고 #32 를 close 하였습니다.

**Comment by makerdark98** [comment]
neighborhood 의 존재가 불필요하다는 근거 메모:
- neighborhood 와 resident 는 composite 패턴으로 cell 로 취급되고 있다.
- 하지만, 이 구조는 composite 패턴을 학습하기 위함이지 실제로 composite 패턴이 적합하지 않다.:
  - 근거 1 : resident 가 자신의 다음 상태를 알아내기 위해서 인접한 셀들을 얻어와야한다. 하지만 neighborhood 의 내부에서만 판단이 불가하여, neighborhood 의 옆 이 필요하며, 이를 위해 direction 이라는 추가적인 클래스가 필요하다.
  - 근거 2 : neighborhood 는 grid 사이즈가 조정되어 있으며 정사각형태가 아닌 직사각형태의 board 를 구성하지 못하게 된다.
  - 근거 3 : ui 와 model 이 분리된 이 시점에서, neighborhood 의 역할은 단순히 ui 와의 중재자 역할밖에 하지 못한다.
  - 근거 4 : neighborhood 는 지나치게 구조를 복잡하게 만들며, 기능확장을 위해 direction, neighborhood, resident 모든 클레스의 내용을 완전히 숙지해야하며, 확장을 위해 Neighborhood 에 메서드를 추가하려면 Cell 에도 추가해야하며, resident 도 변화해야 해서 변경사항이 증가하며 전파하여 코딩 난이도를 높인다.

- 위와 같은 근거로, neighborhood 는 삭제하며, cell 은 resident 만 존재하기 때문에 resident 를 삭제, cell 로 변화시킨다.
