### ISSUE TITLE
테스트 케이스 작성

### ISSUE THREAD

**Issue by sikutisa** [cau-design-pattern-team-10/design-pattern-team-10#4]
* General한 패턴에 대한 테스트 케이스를 수동으로 생성
* https://en.wikipedia.org/wiki/Conway%27s_Game_of_Life
* 각 패턴에 대한 모습을 tick 단위로 생성 및 저장 (5~10tick 정도?)

**Comment by sikutisa** [comment]
테스트 케이스에 대한 추가적인 논의 필요

**Comment by makerdark98** [comment]
예시 : 벽에 부딧히는 경우들에 대한 엣지케이스가 존재해야하는가?

**Comment by makerdark98** [comment]
논의 결과 : 엣지케이스의 경우 게임 규칙 자체를 테스트하고 있다고 판단되어, 현 단계에서 논의하지 않기로 결정
