### ISSUE TITLE
Holub Life source code 깃헙에 추가해두기

### ISSUE THREAD

**Issue by MAYLEAF** [cau-design-pattern-team-10/design-pattern-team-10#5]
* ASIS
Empty Project이며, 각자 Holub like source code를 다운받아서 프로젝트 코드를 확인하고 있다.
* TOBE
동일한 환경에서 작업하고, 코드를 확인할 수 있도록 설정이 되어야한다.  
기본 코드 베이스인 Holub Life source code를 intellij gradle project 세팅에서 재생될 수 있도록 폴더 구조에 넣어주는 작업 진행이 필요하다.

**Comment by makerdark98** [comment]
holub life source code 가 존재하지 않는 것으로 확인됩니다.
코드를 추가한 이후 다시 닫아주세요.
