### ISSUE TITLE
현재 상태 표시(Halt, Slow, Fast etc..)

### ISSUE THREAD

**Issue by MAYLEAF** [cau-design-pattern-team-10/design-pattern-team-10#50]
Life game이 진행되다보면 현재의 속도가 몇인지 알기 어려운 이슈를 마주친다.
두가지 예시를 들어보자면  첫 번재로 Slow인지 Fast인지 현재 상태를 구분하기가 어렵다. 
두 번째로 생태계가 멈춰있는 것처럼 disruptive 상태가 변화가 없을 경우 Halt처럼 보일때도 있다. 
Halt가 아닌데 Halt처럼 인식하여 몇가지 포인트를 클릭해서 패턴을 주고자하면, 생태계가 다시 돌아가기 시작하면서 원래 의도했던 바와 다르게 동작한다.

따라서 현재 속도 상태를 JFrame위에서 볼 수 있도록 rendering 하는 코드를 추가하고자 한다.

**Comment by makerdark98** [comment]
이거, 이슈로 빠져있고, 할당자 있는지 모르고 해서 PR 올렸네요.
한번 봐보시고 피드백해주세요.
