### ISSUE TITLE
Junit 테스트를 위한 테스트코드 작성

### ISSUE THREAD

**Issue by sikutisa** [cau-design-pattern-team-10/design-pattern-team-10#8]
* Junit 테스트 코드 예시를 보고 러프한 테스트 코드 작성
* #4 에서 작성한 테스트 케이스 파일을 로드해서 검증하는 테스트 코드

**Comment by sikutisa** [comment]
해당 이슈 조기종료 시 "Swing UI 테스트"에 대해 리서치

**Comment by makerdark98** [comment]
해당이슈 기본 Unit 테스트 작성하며 완료되었고, 11월 26일 디스코드 회의를 통해 UI 테스트는 화면공유를 통해 진행하기로 결정하여
해당 이슈 완료되어 닫습니다.
